# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment

on:
  push:
    branches: main

jobs:
  deploy-contract:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # solves issue https://github.com/actions/setup-node/issues/214
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Cache Contract
        id: cache-contract
        uses: actions/cache@v2
        with:
          path: prime-numbers
          key: ${{ runner.os }}-${{ hashFiles('contracts/**') }}
      - name: Create env file
        if: steps.cache-contract.outputs.cache-hit != 'true'
        run: >
          echo "ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> ./.env
          && echo "MNEMONIC=${{ secrets.MNEMONIC }}" >> ./.env
      - run: npm ci
        if: steps.cache-contract.outputs.cache-hit != 'true'
      - name: Deploy
        if: steps.cache-contract.outputs.cache-hit != 'true'
        run: npm run deploy-goerli
      - uses: actions/upload-artifact@v2
        if: steps.cache-contract.outputs.cache-hit != 'true'
        with:
          name: contract-deployment-folder
          path: deployments

  deploy-server:
    runs-on: ubuntu-latest
    needs: deploy-contract
    steps:
      - name: Set APP_NAME environment variable
        run: echo "APP_NAME=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: contract-deployment-folder
          path: ${{ github.event.repository.name }}/deployments
          search_artifacts: true
          workflow_conclusion: "completed"
      - name: Display structure of downloaded files
        run: ls ${{ github.event.repository.name }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: ./${{ github.event.repository.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:latest
          build-args: |
            MNEMONIC=${{ secrets.MNEMONIC }}
            ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}
      - name: Configure kubernetes.yml
        run: >
          sed -i "s/\$APP_NAME/${{ env.APP_NAME }}/g" ${{ github.event.repository.name }}/kubernetes.yml
          && sed -i "s/\$DOCKERHUB_USERNAME/${{ secrets.DOCKERHUB_USERNAME }}/g" ${{ github.event.repository.name }}/kubernetes.yml
          && sed -i "s/\$FIREBASE_CREDENTIALS/${{ secrets.FIREBASE_CREDENTIALS }}/g" ${{ github.event.repository.name }}/kubernetes.yml
          && sed -i "s/\$POSTGRES_USER/${{ secrets.POSTGRES_USER }}/g" ${{ github.event.repository.name }}/kubernetes.yml
          && sed -i "s/\$POSTGRES_PASSWORD/${{ secrets.POSTGRES_PASSWORD }}/g" ${{ github.event.repository.name }}/kubernetes.yml
          && sed -i "s/\$POSTGRES_DB/${{ secrets.POSTGRES_DB }}/g" ${{ github.event.repository.name }}/kubernetes.yml
          && sed -i "s/\$POSTGRES_HOST/${{ secrets.POSTGRES_HOST }}/g" ${{ github.event.repository.name }}/kubernetes.yml
      - name: Create wallet-firebase-secrets.yml
        env:
          FIREBASE_SECRETS_YML: ${{ secrets.FIREBASE_SECRETS_YML }}
        run: echo "$FIREBASE_SECRETS_YML" > ${{ github.event.repository.name }}/wallet-firebase-secrets.yml
      - name: Debug
        run: cat ${{ github.event.repository.name }}/kubernetes.yml
      - name: Delete secrets from okteto
        uses: steebchen/kubectl@v2.0.0
        continue-on-error: true
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: delete -f ${{ github.event.repository.name }}/wallet-firebase-secrets.yml
      - name: Apply secrets to okteto
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply -f ${{ github.event.repository.name }}/wallet-firebase-secrets.yml
      - name: Delete deployment from okteto
        uses: steebchen/kubectl@v2.0.0
        continue-on-error: true
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: delete -f ${{ github.event.repository.name }}/kubernetes.yml
      - name: Apply deployment to okteto
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply -f ${{ github.event.repository.name }}/kubernetes.yml
